name: Build Chromium Android with Adblock Plus

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 git lsb-release sudo ccache
          ccache -M 10G  # Dùng cache 10GB để tăng tốc build

      - name: Enable Swap (Avoid Out of Memory)
        run: |
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Restore ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: chromium-ccache-${{ github.run_id }}
          restore-keys: |
            chromium-ccache-

      - name: Setup depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH

      - name: Fetch Chromium source
        run: |
          fetch --nohooks android
          cd src
          gclient sync --nohooks --jobs 16
          ./build/install-build-deps-android.sh
          gclient runhooks

      - name: Integrate Adblock Plus (libadblockplus)
        run: |
          cd src
          git clone https://github.com/adblockplus/libadblockplus.git third_party/adblockplus
          echo 'third_party/adblockplus' >> .gitignore  # Không cần sync lại repo này

      - name: Generate build files
        run: |
          cd src
          gn gen out/Default --args='
            target_os="android"
            target_cpu="arm64"
            enable_extensions=true
            enable_declarative_net_request_api=true
            is_component_build=false
            use_goma=false
          '

      # Chạy build tuần tự thay vì song song
      - name: Build base
        run: cd src && ninja -C out/Default -j2 base
      - name: Build components
        run: cd src && ninja -C out/Default -j2 components
      - name: Build content
        run: cd src && ninja -C out/Default -j2 content
      - name: Build chrome
        run: cd src && ninja -C out/Default -j2 chrome
      - name: Build net
        run: cd src && ninja -C out/Default -j2 net
      - name: Build gpu
        run: cd src && ninja -C out/Default -j2 gpu
      - name: Build media
        run: cd src && ninja -C out/Default -j2 media
      - name: Build ui
        run: cd src && ninja -C out/Default -j2 ui
      - name: Build v8
        run: cd src && ninja -C out/Default -j2 v8
      - name: Build weblayer
        run: cd src && ninja -C out/Default -j2 weblayer

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Package Chromium APK
        run: |
          cd src
          ninja -C out/Default chrome_public_apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Chromium-Adblock-Plus
          path: src/out/Default/apks/Chromium.apk

  release:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: Chromium-Adblock-Plus
          path: release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/Chromium.apk
          tag_name: v1.0.${{ github.run_number }}
          release_name: Chromium Adblock Build v1.0.${{ github.run_number }}
          body: "Chromium Android với hỗ trợ đầy đủ Adblock Plus và bộ lọc cá nhân."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
